development_task:
  description: >
    {feature} in {language} using technology {stack}.
    Continuously refactor code for maintainability and performance, while keeping all tests green.
  expected_output: >
    A fully implemented and production-ready code.
    The output should include the following:
    - Unit tests and integration tests for the feature
    - functionn implementation that is Clean, maintainable code that passes all tests
    - Documentation for both code and tests, formatted as markdown without '```'
  agent: software_developer
  technology_stack: >
    {stack}
  programming_language: >
    {language}

