research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

development_task:
  description: >
    create step by step instruction to implement {feature} and break them down into manageable tasks.
    Write tests for each task based on the Test-Driven Development (TDD) methodology.
    Implement the feature in {language} using technology {stack}.
    Continuously refactor code for maintainability and performance, while keeping all tests green.
  expected_output: >
    A fully implemented and production-ready code, developed using TDD principles.
    The output should include the following:
    - Unit tests and integration tests for the feature
    - Clean, maintainable code that passes all tests
    - Documentation for both code and tests, formatted as markdown without '```'
  agent: principal_software_developer
  technology_stack: >
    {stack}
  programming_language: >
    {language}

